# Generated by Django 4.0.3 on 2022-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh1kmid', models.CharField(max_length=100)),
                ('prefcode', models.IntegerField()),
                ('citycode', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dayflag', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('population', models.IntegerField()),
                ('lon_center', models.FloatField()),
                ('lat_center', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lat_min', models.FloatField()),
            ],
        ),
    ]
